/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sadnessclicker;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.event.ComponentListener;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import org.apache.commons.io.FileUtils;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.TextPage;
import com.gargoylesoftware.htmlunit.UnexpectedPage;
import com.gargoylesoftware.htmlunit.WebClient;

public class Main implements WindowListener, MouseListener, ComponentListener {

    public static final String VERSION = "3.2";
    public static final String[] CHANGELOG = {
        "Added Elias to the closen't screen"
    };

    public static final int ROOM = 20;


    private File file;

    private String workingDirectory;

    private volatile double fileClicks;

    private volatile double clicks;
    private volatile long timeElapsed;

    private volatile long fails;

    private volatile double highScore;

    private volatile double inflation = 1;

    private volatile int elias = 0;

    private volatile boolean cat_mode = false, elias_mode = false, true_elias_mode = false;


    private JFrame frame = new JFrame("Sadness Clicker");
    private JLabel dud =  new JLabel();
    
    public static void main(String[] args) {
        new Main().start();
    }

    public void start() {
        //here, we assign the name of the OS, according to Java, to a variable...
        String OS = (System.getProperty("os.name")).toUpperCase();
        if (OS.contains("WIN")) {
            workingDirectory = System.getenv("AppData");
        }
        else {
            //in either case, we would start in the user's home directory
            workingDirectory = System.getProperty("user.home");
            //if we are on a Mac, we are not done, we look for "Application Support"
            workingDirectory += "/Library/Application Support";
        }
        //we are now free to set the workingDirectory to the subdirectory that is our 
        //folder.
        
        file = new File(workingDirectory + "/SadnessClicker");
        showLoadingWindow();
        loadCat();
        loadElias();
        read();
        make();
    }

    private JLabel loadingLabel = new JLabel("<html><h1>loading...</h1>this should only take a bit...<br />also make sure you're connected to the internet</html>");

    private void showLoadingWindow() {
        frame.getContentPane().removeAll();
        loadingLabel.setBounds(Main.ROOM, Main.ROOM, 200, 100);
        frame.getContentPane().add(loadingLabel);

        frame.setSize(200 + Main.ROOM * 2, 100 + Main.ROOM * 2);
        frame.setVisible(true);
    }

    private void read() {
        try {
            if (!file.exists()) {
                file.createNewFile();
                clicks = 0;
                timeElapsed = 0;
                fails = 0;
            } else {
                FileReader fr = new FileReader(file);
                char[] rawdata = new char[80];
                fr.read(rawdata);
                fr.close();
                String[] data = new String(rawdata).split(",");
                try {
                    clicks = Double.parseDouble(data[0]);
                } catch (IndexOutOfBoundsException | NumberFormatException e) {
                    clicks = 0;
                }
                fileClicks = clicks;
                try {
                    timeElapsed = Long.parseLong(data[1]);
                } catch (IndexOutOfBoundsException | NumberFormatException e) {
                    timeElapsed = 0;
                }
                try {
                    fails = Long.parseLong(data[2]);
                } catch (IndexOutOfBoundsException | NumberFormatException e) {
                    fails = 0;
                }
                try {
                    highScore = Double.parseDouble(data[3]);
                    if (highScore < clicks) {
                        clicks = 0;
                        highScore = 0;
                        fails++;
                        save();
                        JOptionPane.showMessageDialog(null, "Save Data tampering detected, score reset to 0 >:D", "hmmm", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IndexOutOfBoundsException | NumberFormatException e) {
                    highScore = 0;
                }
                try {
                    inflation = Double.parseDouble(data[4]);
                } catch (IndexOutOfBoundsException | NumberFormatException e) {
                    inflation = 1;
                }
                try {
                    if (data[5].equalsIgnoreCase("ELIAS IS WATCHING"))
                        eliasOn();
                } catch (IndexOutOfBoundsException e) {}
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Cannot Access Save Data", "sadness", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
    }

    private void save() {
        save(true);
    }

    private void save(boolean includeClicks) {
        try (FileWriter fw = new FileWriter(file)) {
            if (includeClicks) {
                fw.write(clicks + "," + timeElapsed + "," + fails + "," + highScore + "," + inflation + "," + ((true_elias_mode)? "ELIAS IS WATCHING" : "") + ",");
                fw.close();
                fileClicks = clicks;
            } else {
                fw.write(fileClicks + "," + timeElapsed + "," + fails + "," + highScore + "," + inflation + "," + ((true_elias_mode)? "ELIAS IS WATCHING" : "") + ",");
                fw.close();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Cannot Access Save Data", "sadness", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
    }

    private File cat_file, elias_file, wrong_again;

    private void loadCat() {
        try {
            WebClient client = new WebClient(BrowserVersion.CHROME);
            client.getOptions().setCssEnabled(false);
            client.getOptions().setAppletEnabled(false);
            client.getOptions().setJavaScriptEnabled(false);
            client.getOptions().setTimeout(5000);
            int number = Integer.parseInt(((TextPage) client.getPage("https://raw.githubusercontent.com/Canary-Prism/SadnessClicker/main/cats.csv")).getContent());

            UnexpectedPage image_page = client.getPage("https://raw.githubusercontent.com/Canary-Prism/SadnessClicker/main/cat" + (int)(Math.random() * (double) number) + ".jpg");
            InputStream image_stream = image_page.getInputStream();
            cat_file = new File(workingDirectory + "/SadnessCatClicker.jpg");
            FileUtils.copyInputStreamToFile(image_stream, cat_file);
            cat_file.deleteOnExit();
        } catch (Exception e) {
            String message = "";
            for (StackTraceElement ste : e.getStackTrace()) {
                message += "\n" + ste.toString();
            }
            JOptionPane.showMessageDialog(null, "Failed loading some assets: \n\"" + e + "\n" + message + "\"\nThis isn't strictly required so i'm ignoring this error", "What?", JOptionPane.ERROR_MESSAGE);
            cat_file = null;
        }
    }

    private void loadElias() {
        try {
            WebClient client = new WebClient(BrowserVersion.CHROME);
            client.getOptions().setCssEnabled(false);
            client.getOptions().setAppletEnabled(false);
            client.getOptions().setJavaScriptEnabled(false);
            client.getOptions().setTimeout(5000);
            int number = Integer.parseInt(((TextPage) client.getPage("https://raw.githubusercontent.com/Canary-Prism/SadnessClicker/main/Elias.csv")).getContent());

            UnexpectedPage image_page = client.getPage("https://raw.githubusercontent.com/Canary-Prism/SadnessClicker/main/Elias" + (int)(Math.random() * (double) number) + ".jpg");
            InputStream image_stream = image_page.getInputStream();
            elias_file = new File(workingDirectory + "/SadnessEliasClicker.jpg");
            FileUtils.copyInputStreamToFile(image_stream, elias_file);
            elias_file.deleteOnExit();

            UnexpectedPage wrong_again_page = client.getPage("https://raw.githubusercontent.com/Canary-Prism/SadnessClicker/main/wrong_again.jpg");

            wrong_again = new File(workingDirectory, "/SadnessWrongClicker.jpg");
            FileUtils.copyInputStreamToFile(wrong_again_page.getInputStream(), wrong_again);
            wrong_again.deleteOnExit();
        } catch (Exception e) {
            String message = "";
            for (StackTraceElement ste : e.getStackTrace()) {
                message += "\n" + ste.toString();
            }
            JOptionPane.showMessageDialog(null, "Failed loading some assets: \n\"" + e + "\n" + message + "\"\nThis isn't strictly required so i'm ignoring this error", "What?", JOptionPane.ERROR_MESSAGE);
            elias_file = null;
        }
    }

    private JLabel clicksLabel;
    private JLabel timeLabel;
    private JLabel failsLabel;
    private JLabel highLabel;

    private JButton clickButton = new JButton("Click");
    private JButton wrongButton = new JButton();
    private JLabel wrongLabel = new JLabel("Hello :D");
    private JButton saveButton = new JButton("Save your precious progress");

    private JButton aboutButton = new JButton("about");

    private void make() {
        clicksLabel = new JLabel("Number of clicks: " + clicks);
        timeLabel = new JLabel("Hold on...");
        failsLabel = new JLabel("Number of slip-ups: " + fails);
        highLabel = new JLabel("High Score: " + highScore);

        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.addWindowListener(this);
        frame.setResizable(false);
        frame.addComponentListener(this);

        clicksLabel.setBounds(30, 100, 1000, 30);
        timeLabel.setBounds(30, 130, 1000, 30);
        failsLabel.setBounds(30, 160, 1000, 30);
        highLabel.setBounds(30, 190, 1000, 30);

        clickButton.addMouseListener(this);
        wrongButton.addMouseListener(this);
        aboutButton.addMouseListener(this);
        saveButton.addMouseListener(this);

        wrongButton.setOpaque(false);
        wrongButton.setContentAreaFilled(false);
        wrongButton.setBorderPainted(false);
        wrongButton.setFocusPainted(false);

        clickButton.setBounds(225, 225, 50, 50);
        wrongButton.setBounds(-10, -10, 520, 520);
        wrongLabel.setBounds(50, 275, 1000, 100);

        saveButton.setBounds(280, 30, 220, 30);
        
        aboutButton.setBounds(380, 400, 100, 30);

        aboutLabel.setBounds(30, 30, 400, 200);

        changelogButton.addMouseListener(this);
        backButton.addMouseListener(this);

        changelogButton.setBounds(20, 230, 100, 30);
        versionLabel.setBounds(120, 230, 100, 30);

        String temp = "<html><h1>Changelog</h1>" + Main.VERSION;
        for (int i = 0; i < Main.CHANGELOG.length; i++) {
            temp += "<br />•" + Main.CHANGELOG[i];
        }
        temp += "</html>";

        changelogLabel.setText(temp);
        changelogLabel.setVerticalAlignment(SwingConstants.TOP);
        changelogLabel.setBounds(0, 0, 400, Main.CHANGELOG.length * 40 + 50);


        Runnable timerClock = new Runnable() {
            public void run() {
                timeElapsed += 1;
                timeLabel.setText(
                    "Time you've wasted: " + 
                    String.valueOf(TimeUnit.SECONDS.toDays(timeElapsed)) + ":" +
                    String.valueOf(TimeUnit.SECONDS.toHours(timeElapsed) - ((TimeUnit.SECONDS.toDays(timeElapsed) *24))) + ":" +
                    String.valueOf(TimeUnit.SECONDS.toMinutes(timeElapsed) - (TimeUnit.SECONDS.toHours(timeElapsed)* 60)) + ":" +
                    String.valueOf(TimeUnit.SECONDS.toSeconds(timeElapsed) - (TimeUnit.SECONDS.toMinutes(timeElapsed) *60))
                );
                save(false);
            }
        };

        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        executor.scheduleAtFixedRate(timerClock, 0, 1, TimeUnit.SECONDS);

        showMain();
    }

    private void showMain() {
        frame.getContentPane().removeAll();
        frame.setSize(500, 500);

        frame.getContentPane().add(aboutButton);

        frame.getContentPane().add(saveButton);
        
        frame.getContentPane().add(clicksLabel);
        frame.getContentPane().add(timeLabel);
        frame.getContentPane().add(failsLabel);
        frame.getContentPane().add(highLabel);

        frame.getContentPane().add(wrongLabel);
        frame.getContentPane().add(clickButton);
        frame.getContentPane().add(wrongButton);
        frame.getContentPane().add(dud);

        frame.setVisible(true);
    }

    private JLabel aboutLabel = new JLabel("<html><h1>About</h1><br />Hi! i'm Canary :3<br />This is a pointless little app that I made to cause suffering :D<br />If you're looking for a useful thing, this ain't it mate. In fact, most of my things are pretty useless...<br />However, this is the first thing i made with save data functionality! <b>YAY!<br /></html>");

    private JButton changelogButton = new JButton("Changelog");
    private JButton backButton = new JButton("Back");
    private JLabel versionLabel = new JLabel(Main.VERSION);

    private void showAboutMenu() {
        frame.getContentPane().removeAll();
        frame.getContentPane().add(aboutLabel);

        backButton.setBounds(300, 230, 100, 30);


        frame.getContentPane().add(changelogButton);
        frame.getContentPane().add(versionLabel);
        frame.getContentPane().add(backButton);

        frame.getContentPane().add(dud);
        frame.setSize(500, 300);
        frame.repaint();
    }

    private JLabel changelogLabel = new JLabel();

    private void showChangelog() {
        frame.getContentPane().removeAll();

        frame.getContentPane().add(backButton, BorderLayout.PAGE_END);

        frame.getContentPane().add(changelogLabel);
        frame.getContentPane().add(dud);

        frame.setResizable(true);
        frame.setSize(420, Main.CHANGELOG.length * 30 + 160);
    }

    private void catsOn() {
        dud.setIcon(new ImageIcon(new ImageIcon(cat_file.getAbsolutePath()).getImage().getScaledInstance(500, 500, Image.SCALE_SMOOTH)));
        cat_mode = true;
    }

    private void catsOff() {
        if (true_elias_mode)
            return;
        
        dud.setIcon(null);
        cat_mode = false;
    }

    private void eliasOn() {
        catsOff();
        aboutLabel.setText("<html>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br />IT NEVER ENDS<br /><br />THE COMMUNIST UPRISING<br />WE WILL OVERTHROW THE CAPITALIST GOVERNMENT</html>");
        versionLabel.setText("e̷͍͕͍̮͒̒͆̿͂̀̇̋͜͠l̸̫͍̼̏͋̇̊̎͝͠͝ȋ̷͎͔͕̟̤̭̮̫̪͎̬̬̥̜a̸͍̩̞̠͕̬̐̾̎̈͘s̴̲͍̙͉̉");
        frame.setTitle("THE COMMUNIST UPRISING");
        inflation = 3.141592653589793238462643383279;
        dud.setIcon(new ImageIcon(new ImageIcon(elias_file.getAbsolutePath()).getImage().getScaledInstance(500, 500, Image.SCALE_SMOOTH)));
        aboutButton.setText("AAAAA");
        clicks = 0;
        elias_mode = false;
        true_elias_mode = true;
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if (!SwingUtilities.isLeftMouseButton(e) && (e.getSource() == clickButton || e.getSource() == aboutButton)) {
            if (elias_mode)
                return;

            catsOff();
            clicks = 0;
            fails++;
            failsLabel.setText("Number of slip-ups: " + fails);
            clicksLabel.setText("Number of clicks: 0 :O");
            highLabel.setText("High Score: " + highScore + ">:3");
            wrongLabel.setText("<html><h2>Welp. your clicks are now reset</h2><br />at least you learned something<br />next time remember not to right click ;D</html>");
            save();
            return;
        }
        if (e.getSource() == clickButton) {
            if (clicks >= 0)
                clicks += inflation;

            if (elias == 20 && !true_elias_mode) {
                aboutButton.setText("Elias");
                elias_mode = true;
            }
            highLabel.setText("High Score: " + String.format("%.1f", highScore) + "0");
            if (highScore < clicks) {
                highScore = clicks;
                highLabel.setText("High Score: " + String.format("%.1f", highScore) + "0 :D");
            }
            clicksLabel.setText("Number of clicks: " + String.format("%.1f", clicks) + "0");
            wrongLabel.setText("good job");

            if (cat_mode)
                inflation -= 0.001;
            if (clicks >= 1000 && !cat_mode) {
                wrongLabel.setText("WOO HOO! 1000 CLICKS!!!!! :3");
                catsOn();
            }

            if (clicks < 0) {
                elias++;
                wrongLabel.setText("what happened??");
                clicksLabel.setText("Number of clicks: EEEEEEEEE");
            }

            if (true_elias_mode) {
                wrongLabel.setText("HEHEHEHEHEHE");
            }


            switch ((int)(Math.random() * 10)) {
                case 0 -> 
                    clickButton.setLocation(clickButton.getX() + (int)(Math.random() * 15), clickButton.getY());
                case 1 -> 
                    clickButton.setLocation(clickButton.getX() - (int)(Math.random() * 15), clickButton.getY());
                case 2 -> 
                    clickButton.setLocation(clickButton.getX(), clickButton.getY() + (int)(Math.random() * 15));
                case 3 -> 
                    clickButton.setLocation(clickButton.getX(), clickButton.getY() - (int)(Math.random() * 15));
            }
            if (clickButton.getX() + 50 < 0 || clickButton.getX() > 500 || clickButton.getY() + 50 < 0 || clickButton.getY() > 500)
                clickButton.setLocation(225, 225);
        }
        if (e.getSource() == wrongButton) {
            if (elias_mode)
                return;
            catsOff();
            clicks = 0;
            fails++;
            failsLabel.setText("Number of slip-ups: " + fails);
            clicksLabel.setText("Number of clicks: 0 :O");
            highLabel.setText("High Score: " + highScore + ">:3");
            wrongLabel.setText("<html><h2>Welp. your clicks are now reset</h2><br />next time remember to not click here</html>");
            save();
        }
        if (e.getSource() == aboutButton) {
            if (!elias_mode) 
                showAboutMenu();
            else {
                aboutButton.setText("AAAAA");
                eliasOn();
            }
        }
        if (e.getSource() == backButton) {
            frame.setResizable(false);
            showMain();
        }
        if (e.getSource() == changelogButton) {
            frame.setResizable(true);
            showChangelog();
        }
        if (e.getSource() == saveButton)  {
            if (Math.random() > 0.3)
                saveButton.setBounds(280, 30, 220, 30);
            else
                saveButton.setBounds(20, 30, 220, 30);
            if (Math.random() > 0.001) {
                wrongLabel.setText("<html><h1>Saving...</h1> or not...<br />it cost 1 click point!</html>");
                clicks = (clicks >= 1)? clicks - 1 : clicks;
            } else {
                wrongLabel.setText("<html><h1>Saving...</h1> or not...<br />it cost <b>100</b> click points!<br />Lucky!!</html>");
                clicks = (clicks >= 100)? clicks - 100 : 0;
            }
            clicksLabel.setText("Number of clicks: " + String.format("%.1f", clicks) + "0");
            if (Math.random() > 0.3)
                save();
        }
    }

    @Override
    public void windowClosing(WindowEvent e) {
        if (!true_elias_mode) {
            frame.dispose();
            save(false);
            JOptionPane.showMessageDialog(null, "Until next time ;D");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "WRONG AGAIN", "e̷͍͕͍̮͒̒͆̿͂̀̇̋͜͠l̸̫͍̼̏͋̇̊̎͝͠͝ȋ̷͎͔͕̟̤̭̮̫̪͎̬̬̥̜a̸͍̩̞̠͕̬̐̾̎̈͘s̴̲͍̙͉̉", JOptionPane.PLAIN_MESSAGE, new ImageIcon(new ImageIcon(wrong_again.getAbsolutePath()).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
        }
    }

    @Override
    public void windowOpened(WindowEvent e) {        
    }

    @Override
    public void windowClosed(WindowEvent e) {        
    }

    @Override
    public void windowIconified(WindowEvent e) {        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {        
    }

    @Override
    public void windowActivated(WindowEvent e) {        
    }

    @Override
    public void windowDeactivated(WindowEvent e) {        
    }

    @Override
    public void mouseClicked(MouseEvent e) {        
    }

    @Override
    public void mouseReleased(MouseEvent e) {        
    }

    @Override
    public void mouseEntered(MouseEvent e) {        
    }

    @Override
    public void mouseExited(MouseEvent e) {        
    }

    @Override
    public void componentResized(ComponentEvent e) {
        changelogLabel.setBounds(0, 0, e.getComponent().getWidth() - 20, e.getComponent().getHeight() - 20); 
    }

    @Override
    public void componentMoved(ComponentEvent e) {
    }

    @Override
    public void componentShown(ComponentEvent e) {
    }

    @Override
    public void componentHidden(ComponentEvent e) {
    }
}
